[package]
name = "financial_report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.6", features = ["headers"] }
tokio = { version = "1.18.2", features = ["full"] }
dotenvy = "0.15.1"
anyhow = "1.0.57"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
