version: '3'

services:
    postgres:
        container_name: postgres
        image: "postgres:latest"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: financial_reports
        ports:
            - 5432:5432
        volumes:
            - "postgres-financial-reports:/var/lib/postgresql/data"

    redis:
        container_name: redis
        restart: always
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "redis-financial-reports:/data"

volumes:
    postgres-financial-reports:
    redis-financial-reports:
