version: '3'

services:
    postgres:
        container_name: test_postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=financial_reports
        volumes:
            - data:/var/lib/postgresql/data
        restart: "always"

volumes:
    data: