version: '3'

services:
    postgres:
        container_name: test_postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=financial_reports
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: "always"

    redis:
        container_name: test_redis
        image: redis
        ports:
            - "6379:6379"
        restart: "always"
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
