[package]
name = "infrastructures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
applications = { path = "../applications" }
domain = { path = "../domain" }
presentation = { path = "../presentation" }
anyhow = "1.0.58"
